/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


/**
 *
 * @author jhessikkaelly
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */

    
    public TelaPrincipal() {
        initComponents();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PainelTelaPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        areaDeCalculo = new javax.swing.JTextField();
        multiplicacao = new javax.swing.JButton();
        divisao = new javax.swing.JButton();
        soma = new javax.swing.JButton();
        subtracao = new javax.swing.JButton();
        porcentagem = new javax.swing.JButton();
        sete = new javax.swing.JButton();
        quatro = new javax.swing.JButton();
        um = new javax.swing.JButton();
        oito = new javax.swing.JButton();
        nove = new javax.swing.JButton();
        virgula = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        dois = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        parenteses = new javax.swing.JButton();
        limparTudo = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        igual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PainelTelaPrincipal.setBackground(new java.awt.Color(102, 255, 102));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setText("Calculadora DevMat");

        areaDeCalculo.setEditable(false);
        areaDeCalculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        areaDeCalculo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        multiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        multiplicacao.setText("x");
        multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacaoActionPerformed(evt);
            }
        });

        divisao.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        divisao.setText("/");
        divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisaoActionPerformed(evt);
            }
        });

        soma.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        soma.setText("+");
        soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaActionPerformed(evt);
            }
        });

        subtracao.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        subtracao.setText("-");
        subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtracaoActionPerformed(evt);
            }
        });

        porcentagem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        porcentagem.setText("%");
        porcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentagemActionPerformed(evt);
            }
        });

        sete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        sete.setText("7");
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });

        quatro.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        quatro.setText("4");
        quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroActionPerformed(evt);
            }
        });

        um.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        um.setText("1");
        um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umActionPerformed(evt);
            }
        });

        oito.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        oito.setText("8");
        oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoActionPerformed(evt);
            }
        });

        nove.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });

        virgula.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        virgula.setText(",");
        virgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virgulaActionPerformed(evt);
            }
        });

        apagar.setIcon(new javax.swing.ImageIcon("C:\\Users\\jhessikkaelly\\Documents\\NetBeansProjects\\CalculadoraMat\\src\\main\\java\\imagens\\cancelar.png")); // NOI18N
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });

        cinco.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        dois.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        dois.setText("2");
        dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisActionPerformed(evt);
            }
        });

        seis.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        parenteses.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        parenteses.setText("( )");
        parenteses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesesActionPerformed(evt);
            }
        });

        limparTudo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        limparTudo.setText("AC");
        limparTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTudoActionPerformed(evt);
            }
        });

        tres.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        zero.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        igual.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelTelaPrincipalLayout = new javax.swing.GroupLayout(PainelTelaPrincipal);
        PainelTelaPrincipal.setLayout(PainelTelaPrincipalLayout);
        PainelTelaPrincipalLayout.setHorizontalGroup(
            PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(multiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(soma, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtracao, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(porcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                                .addComponent(quatro, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cinco, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seis, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(parenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limparTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE))
                            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                                .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(oito, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nove, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                                .addComponent(um, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dois, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tres, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(igual, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))))
                    .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areaDeCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(96, 96, 96))
            .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(divisao, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGap(330, 330, 330)))
        );
        PainelTelaPrincipalLayout.setVerticalGroup(
            PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(areaDeCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(soma, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(subtracao, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(porcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oito, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(um, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dois, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
            .addGroup(PainelTelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelTelaPrincipalLayout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(divisao, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addGap(187, 187, 187)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void divisaoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"/");
        
    }                                       

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"7");
        
    }                                    

    private void quatroActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"4");
    }                                      

    private void umActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // metodo de ação do botão 1
        areaDeCalculo.setText(areaDeCalculo.getText()+"1");
        
        
    }                                  

    private void oitoActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"8");

    }                                    

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"9");
    }                                    

    private void virgulaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+".");
    }                                       

    // botão qua apaga a ultima coisa digitada
    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        // capturando o texto digitado
        String textoAtual = areaDeCalculo.getText();
        // verificar se o texto está vazio ou não
        // se texto for maior que zero
        if(textoAtual.length()>0){
            // então exclua o ultimo caracter digitado
            // substring subdivide a palavra letra por letra
            // substring(posicaoinicial,tamanho,posicaofinal)
            textoAtual = textoAtual.substring
                (0,textoAtual.length()-1);// apagando letra por letra
          areaDeCalculo.setText(textoAtual);  
        }// fim do if
      
    }                                      

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"5");
         
    }                                     

    private void doisActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"2");
        
    }                                    

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"6");
    }                                    
    
    // variavel para verificar se o ( foi aberto
    // inicialmente parentese não foi aberto
    boolean parenteseAberto =false;
    private void parentesesActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        // se parentese ainda não foi aberto
        if (parenteseAberto==false){
            // abra o parentese
            areaDeCalculo.setText(areaDeCalculo.getText() +"(");
            // parentese agora foi aberto
            parenteseAberto=true;
        }else{ // parentese já esta aberto
            // fechando parentese
            areaDeCalculo.setText(areaDeCalculo.getText() +")");
            parenteseAberto=false; // parentese não esta aberto mais
        }

    }                                          

    private void limparTudoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        areaDeCalculo.setText("");
    }                                          

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"3");
    }                                    

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"0");
    }                                    

    // metodo para calcular 
    private double equacao(String expressao){
     // avaliando a expressão matemática
      return new Object(){
          // variavel de percorrer os caracteres
          int posicao = -1 ; 
          int ch;
          
          // avançar os proximos caracteres da expressao
          void nextChar(){
            // variavel do caracteres
            // length() ele verifica o tamanho de um texto
            ch = (++posicao < expressao.length()) ? 
                    expressao.charAt(posicao) : -1; 
          }// final do nextChar()
          
          // verificando os caracteres na proxima posicao
          boolean eat (int valores){
             // percorrendo o vetor até achar o espaço em branco
             while(ch ==' ')nextChar();
             // se ch for um numero então retorne verdadeiro
               if(ch == valores){
                   nextChar();// converta o numero em caracter
                   return true; // retorne verdadeiro
               }else{ // se não retorne falso
                   return false; // retornando falso
               }// final do if else   
          }// final do metodo eat
          
          // metodo para analise principal dos calculos
          double calculando(){
              // chamando o metodo de reconhecimento dos caracteres
              nextChar();
              // criando variavel de calculo x
              double x= somarSubtrair();
              // verificando se existe mais caractere 
              if(posicao<expressao.length()) 
                  // tratando erros do sistema
                  throw new RuntimeException("Erro: "+ (char)ch);
              return x;
          }// final do calculando
          
          
          
          // Análisar as expressões (adição,subtração )
          double somarSubtrair(){
             double x = dividirMultiplicar();
              // for para ir somando  
             for (;;){
                // eat função de comparação de caractere
                // se for + ele vai somando os numeros
                if (eat('+')) x+= dividirMultiplicar(); // adição
                // se não, se for - ele vai subtraindo
                else if (eat('-')) x-= dividirMultiplicar(); // subtração
                // se não ele só retorna
                else return x;
                }
          } // final da soma
          
          // analisar as expressões de dividir e multiplicar
          double dividirMultiplicar(){
             double x =fatores() ;
              // for para ir somando  
             for (;;){
                // eat função de comparação de caractere
                // se for x ele vai multiplica
                if (eat('x')) x*=fatores() ; // adição
                // se não, se for / ele vai dividir
                else if (eat('/')) x/= fatores(); // subtração
                // se não ele só retorna o valor que já temos
                else return x;
                }
          } // fim do dividirMultiplicar
          
          
          // metodo para considerar o calculo dos parenteses 
          double fatores(){
              // pegando o inicio do vetor
            int inicioPosicao = this.posicao;
            // variavel do calculo
            double x = 0;
            // procurando os parenteses (  )
            if(eat('(')){
               x = somarSubtrair();
               eat(')');
           // verificando os numeros digitados
            }else if((ch >= '0' && ch<='9') || ch=='.'){
                while((ch>='0' && ch<='9')|| ch=='.') nextChar();
                // converter os caracteres em numeros
                x = Double.parseDouble(expressao.substring
                   (inicioPosicao, this.posicao));
                 
            }else{
                // tratando erros nas variaveis
                  throw new RuntimeException("Erros:"+ (char)ch);  
            }// final do else
             return x;
          }// final do metodo fatores
          
          

       }.calculando();// final do return new object
          
      }// final do metodo equacao
    
    
    
    private void igualActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // capturar o texto da área de calculo
        // getText() - captura o que tem escrito
        // setText() - escreve algo dentro 
        try{ // se não tiver nenhum erro execute
           String expressaoCalculo = areaDeCalculo.getText();
        // chamando o metodo de calcular e passando o calculo    
        double resultado = equacao(expressaoCalculo);
        // passando o resultado para a área de Calculo
        areaDeCalculo.setText(String.valueOf(resultado));
        }catch(Exception e){ // caso dê erro imprima a msg de erro
            areaDeCalculo.setText("Erro no calculo"+e);
        }
    }                                     

    private void somaActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"+");
    }                                    

    private void subtracaoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"-");
    }                                         

    private void porcentagemActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"%");
    }                                           

    private void multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        areaDeCalculo.setText(areaDeCalculo.getText()+"x");
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel PainelTelaPrincipal;
    private javax.swing.JButton apagar;
    private javax.swing.JTextField areaDeCalculo;
    private javax.swing.JButton cinco;
    private javax.swing.JButton divisao;
    private javax.swing.JButton dois;
    private javax.swing.JButton igual;
    private javax.swing.JButton limparTudo;
    private javax.swing.JButton multiplicacao;
    private javax.swing.JButton nove;
    private javax.swing.JButton oito;
    private javax.swing.JButton parenteses;
    private javax.swing.JButton porcentagem;
    private javax.swing.JButton quatro;
    private javax.swing.JButton seis;
    private javax.swing.JButton sete;
    private javax.swing.JButton soma;
    private javax.swing.JButton subtracao;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton tres;
    private javax.swing.JButton um;
    private javax.swing.JButton virgula;
    private javax.swing.JButton zero;
    // End of variables declaration                   
}
